# site settings
title: FJAN IT
subtitle: 
email: funs@fjan.nl
description: FJAN IT is uw partner voor (MKB) bedrijfssoftware, websites, mobiele apps en meer.
baseurl:
url: https://funselaar.github.io # the base hostname & protocol for your site
domain: funselaar.github.io
author:
street_address: Loolaan 246
city: Apeldoorn
state: Gelderland
zip_code: 7315AH
country: Nederland
phone: +31 6 57 84 28 20

family: Arial

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/funs-janssen/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
