# site settings
title: FJAN IT
subtitle: 
email: info@fjan.nl
description: FJAN IT is uw partner voor (MKB) bedrijfssoftware, websites, mobiele apps en meer.
url: https://fjan.nl
domain: fjan.nl
author:
street_address: Loolaan 246
city: Apeldoorn
state: Gelderland
zip_code: 7315AH
country: Nederland
phone: +31 6 57 84 28 20

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
